//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS499.TCMS.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS499.TCMS.View.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete business partner. Please contact support..
        /// </summary>
        internal static string AllBusinessPartnerDeleteError {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting business partner... Please wait..
        /// </summary>
        internal static string AllBusinessPartnerDeleting {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partners.
        /// </summary>
        internal static string AllBusinessPartnerDisplayName {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify business partners..
        /// </summary>
        internal static string AllBusinessPartnerDisplayToolTip {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load business partners. Please contact support..
        /// </summary>
        internal static string AllBusinessPartnerLoadError {
            get {
                return ResourceManager.GetString("AllBusinessPartnerLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading business partners... Please wait..
        /// </summary>
        internal static string AllBusinessPartnerLoading {
            get {
                return ResourceManager.GetString("AllBusinessPartnerLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete payroll. Please contact support..
        /// </summary>
        internal static string AllPayrollDeleteError {
            get {
                return ResourceManager.GetString("AllPayrollDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting payroll... Please wait..
        /// </summary>
        internal static string AllPayrollDeleting {
            get {
                return ResourceManager.GetString("AllPayrollDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        internal static string AllPayrollDisplayName {
            get {
                return ResourceManager.GetString("AllPayrollDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify payroll..
        /// </summary>
        internal static string AllPayrollDisplayToolTip {
            get {
                return ResourceManager.GetString("AllPayrollDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load payrolls. Please contact support..
        /// </summary>
        internal static string AllPayrollLoadError {
            get {
                return ResourceManager.GetString("AllPayrollLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading payrolls... Please wait..
        /// </summary>
        internal static string AllPayrollLoading {
            get {
                return ResourceManager.GetString("AllPayrollLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user ({0}). Please contact support..
        /// </summary>
        internal static string AllUserDeleteError {
            get {
                return ResourceManager.GetString("AllUserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user... Please wait..
        /// </summary>
        internal static string AllUserDeleting {
            get {
                return ResourceManager.GetString("AllUserDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string AllUserDisplayName {
            get {
                return ResourceManager.GetString("AllUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify users..
        /// </summary>
        internal static string AllUserDisplayToolTip {
            get {
                return ResourceManager.GetString("AllUserDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load users. Please contact support..
        /// </summary>
        internal static string AllUserLoadError {
            get {
                return ResourceManager.GetString("AllUserLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users... Please wait..
        /// </summary>
        internal static string AllUserLoading {
            get {
                return ResourceManager.GetString("AllUserLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string AppSettingsDisplayName {
            get {
                return ResourceManager.GetString("AppSettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to set application settings..
        /// </summary>
        internal static string AppSettingsDisplayToolTip {
            get {
                return ResourceManager.GetString("AppSettingsDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open log file..
        /// </summary>
        internal static string AppSettingsFailedToOpenLog {
            get {
                return ResourceManager.GetString("AppSettingsFailedToOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AssemblyInformationDisplayName {
            get {
                return ResourceManager.GetString("AssemblyInformationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partner: {0}.
        /// </summary>
        internal static string BusinessPartnerDisplayName {
            get {
                return ResourceManager.GetString("BusinessPartnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save business partner ({0}) because it already exists..
        /// </summary>
        internal static string BusinessPartnerSaveError {
            get {
                return ResourceManager.GetString("BusinessPartnerSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving business partner... Please wait..
        /// </summary>
        internal static string BusinessPartnerSaving {
            get {
                return ResourceManager.GetString("BusinessPartnerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string ContentId {
            get {
                return ResourceManager.GetString("ContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the database. Please contact support..
        /// </summary>
        internal static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} ({1})?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download help document. Please contact support..
        /// </summary>
        internal static string HelpDocumentDowloadError {
            get {
                return ResourceManager.GetString("HelpDocumentDowloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate username ({0}). Please enter a valid password..
        /// </summary>
        internal static string LoginFailPassword {
            get {
                return ResourceManager.GetString("LoginFailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) was not found in the Database. Please enter a valid username..
        /// </summary>
        internal static string LoginFailUsername {
            get {
                return ResourceManager.GetString("LoginFailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) not found. Please contact support..
        /// </summary>
        internal static string LoginLoadError {
            get {
                return ResourceManager.GetString("LoginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user settings... Please wait..
        /// </summary>
        internal static string LoginLoading {
            get {
                return ResourceManager.GetString("LoginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Windows username and password to login..
        /// </summary>
        internal static string LoginStart {
            get {
                return ResourceManager.GetString("LoginStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutDisplayName {
            get {
                return ResourceManager.GetString("LogoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log out of the application..
        /// </summary>
        internal static string LogoutDisplayToolTip {
            get {
                return ResourceManager.GetString("LogoutDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for background task to complete before closing or logging out of the application..
        /// </summary>
        internal static string MainWindowBackgroundTask {
            get {
                return ResourceManager.GetString("MainWindowBackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS - {0}.
        /// </summary>
        internal static string MainWindowDisplayName {
            get {
                return ResourceManager.GetString("MainWindowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS - {0} - ({1}).
        /// </summary>
        internal static string MainWindowDisplayNameLoggedIn {
            get {
                return ResourceManager.GetString("MainWindowDisplayNameLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Help Menu..
        /// </summary>
        internal static string MainWindowHelpTooltip {
            get {
                return ResourceManager.GetString("MainWindowHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MainWindowInitialStatus {
            get {
                return ResourceManager.GetString("MainWindowInitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Main Menu..
        /// </summary>
        internal static string MainWindowMenuTooltip {
            get {
                return ResourceManager.GetString("MainWindowMenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed... Please contact support if this error continues to occur..
        /// </summary>
        internal static string MainWindowUnexpectedLoginError {
            get {
                return ResourceManager.GetString("MainWindowUnexpectedLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user name... Please contact support..
        /// </summary>
        internal static string MainWindowUserUnknown {
            get {
                return ResourceManager.GetString("MainWindowUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more unsaved changes were found. Are you sure you want to continue without saving?.
        /// </summary>
        internal static string MainWindowViewModelCheckForChanges {
            get {
                return ResourceManager.GetString("MainWindowViewModelCheckForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll: {0}.
        /// </summary>
        internal static string PayrollDisplayName {
            get {
                return ResourceManager.GetString("PayrollDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll: {0}.
        /// </summary>
        internal static string PayrollDisplayToolTip {
            get {
                return ResourceManager.GetString("PayrollDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save payroll. Please contact support..
        /// </summary>
        internal static string PayrollSaveError {
            get {
                return ResourceManager.GetString("PayrollSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving payroll... Please wait..
        /// </summary>
        internal static string PayrollSaving {
            get {
                return ResourceManager.GetString("PayrollSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by any column..
        /// </summary>
        internal static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeDisplayName {
            get {
                return ResourceManager.GetString("ThemeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify application theme..
        /// </summary>
        internal static string ThemeDisplayToolTip {
            get {
                return ResourceManager.GetString("ThemeDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user theme... Please wait..
        /// </summary>
        internal static string ThemeLoading {
            get {
                return ResourceManager.GetString("ThemeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving theme... Please wait..
        /// </summary>
        internal static string ThemeSaving {
            get {
                return ResourceManager.GetString("ThemeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS.
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while {0}.{1}Please contact support with the following error ID: {2}.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string UserDisplayName {
            get {
                return ResourceManager.GetString("UserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string UserDisplayToolTip {
            get {
                return ResourceManager.GetString("UserDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user ({0}) because it already exists..
        /// </summary>
        internal static string UserSaveError {
            get {
                return ResourceManager.GetString("UserSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user... Please wait..
        /// </summary>
        internal static string UserSaving {
            get {
                return ResourceManager.GetString("UserSaving", resourceCulture);
            }
        }
    }
}
