//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS499.TCMS.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS499.TCMS.View.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete business partner. Please contact support..
        /// </summary>
        internal static string AllBusinessPartnerDeleteError {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting business partner... Please wait..
        /// </summary>
        internal static string AllBusinessPartnerDeleting {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partners.
        /// </summary>
        internal static string AllBusinessPartnerDisplayName {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify business partners..
        /// </summary>
        internal static string AllBusinessPartnerDisplayToolTip {
            get {
                return ResourceManager.GetString("AllBusinessPartnerDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load business partners. Please contact support..
        /// </summary>
        internal static string AllBusinessPartnerLoadError {
            get {
                return ResourceManager.GetString("AllBusinessPartnerLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading business partners... Please wait..
        /// </summary>
        internal static string AllBusinessPartnerLoading {
            get {
                return ResourceManager.GetString("AllBusinessPartnerLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete maintenance part ({0}). Please contact support..
        /// </summary>
        internal static string AllMaintenancePartDeleteError {
            get {
                return ResourceManager.GetString("AllMaintenancePartDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting maintenance part... Please wait..
        /// </summary>
        internal static string AllMaintenancePartDeleting {
            get {
                return ResourceManager.GetString("AllMaintenancePartDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Parts.
        /// </summary>
        internal static string AllMaintenancePartDisplayName {
            get {
                return ResourceManager.GetString("AllMaintenancePartDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify maintenance parts..
        /// </summary>
        internal static string AllMaintenancePartDisplayToolTip {
            get {
                return ResourceManager.GetString("AllMaintenancePartDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load maintenance parts. Please contact support..
        /// </summary>
        internal static string AllMaintenancePartLoadError {
            get {
                return ResourceManager.GetString("AllMaintenancePartLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maintenance parts... Please wait..
        /// </summary>
        internal static string AllMaintenancePartLoading {
            get {
                return ResourceManager.GetString("AllMaintenancePartLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete maintenance record ({0}). Please contact support..
        /// </summary>
        internal static string AllMaintenanceRecordDeleteError {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting maintenance record... Please wait..
        /// </summary>
        internal static string AllMaintenanceRecordDeleting {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete maintenance record detail. Please contact support..
        /// </summary>
        internal static string AllMaintenanceRecordDetailDeleteError {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting maintenance record detail... Please wait..
        /// </summary>
        internal static string AllMaintenanceRecordDetailDeleting {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Record Details.
        /// </summary>
        internal static string AllMaintenanceRecordDetailDisplayName {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify maintenance record details..
        /// </summary>
        internal static string AllMaintenanceRecordDetailDisplayToolTip {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load maintenance record details. Please contact support..
        /// </summary>
        internal static string AllMaintenanceRecordDetailLoadError {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maintenance record details... Please wait..
        /// </summary>
        internal static string AllMaintenanceRecordDetailLoading {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDetailLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Records.
        /// </summary>
        internal static string AllMaintenanceRecordDisplayName {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify maintenance records..
        /// </summary>
        internal static string AllMaintenanceRecordDisplayToolTip {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load maintenance records. Please contact support..
        /// </summary>
        internal static string AllMaintenanceRecordLoadError {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maintenance records... Please wait..
        /// </summary>
        internal static string AllMaintenanceRecordLoading {
            get {
                return ResourceManager.GetString("AllMaintenanceRecordLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete manifest ({0}). Please contact support..
        /// </summary>
        internal static string AllManifestDeleteError {
            get {
                return ResourceManager.GetString("AllManifestDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting manifest. Please wait..
        /// </summary>
        internal static string AllManifestDeleting {
            get {
                return ResourceManager.GetString("AllManifestDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifests.
        /// </summary>
        internal static string AllManifestDisplayName {
            get {
                return ResourceManager.GetString("AllManifestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify manifests..
        /// </summary>
        internal static string AllManifestDisplayToolTip {
            get {
                return ResourceManager.GetString("AllManifestDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load manifest. Please wait..
        /// </summary>
        internal static string AllManifestLoadError {
            get {
                return ResourceManager.GetString("AllManifestLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading manifests... Please wait..
        /// </summary>
        internal static string AllManifestLoading {
            get {
                return ResourceManager.GetString("AllManifestLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete part ({0}). Please contact support..
        /// </summary>
        internal static string AllPartDeleteError {
            get {
                return ResourceManager.GetString("AllPartDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting part... Please wait..
        /// </summary>
        internal static string AllPartDeleting {
            get {
                return ResourceManager.GetString("AllPartDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string AllPartDisplayName {
            get {
                return ResourceManager.GetString("AllPartDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify parts..
        /// </summary>
        internal static string AllPartDisplayToolTip {
            get {
                return ResourceManager.GetString("AllPartDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load parts. Please contact support..
        /// </summary>
        internal static string AllPartLoadError {
            get {
                return ResourceManager.GetString("AllPartLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading parts... Please wait..
        /// </summary>
        internal static string AllPartLoading {
            get {
                return ResourceManager.GetString("AllPartLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete payroll. Please contact support..
        /// </summary>
        internal static string AllPayrollDeleteError {
            get {
                return ResourceManager.GetString("AllPayrollDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting payroll... Please wait..
        /// </summary>
        internal static string AllPayrollDeleting {
            get {
                return ResourceManager.GetString("AllPayrollDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        internal static string AllPayrollDisplayName {
            get {
                return ResourceManager.GetString("AllPayrollDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify payroll..
        /// </summary>
        internal static string AllPayrollDisplayToolTip {
            get {
                return ResourceManager.GetString("AllPayrollDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load payrolls. Please contact support..
        /// </summary>
        internal static string AllPayrollLoadError {
            get {
                return ResourceManager.GetString("AllPayrollLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading payrolls... Please wait..
        /// </summary>
        internal static string AllPayrollLoading {
            get {
                return ResourceManager.GetString("AllPayrollLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete purchase item ({0}). Please contact support..
        /// </summary>
        internal static string AllPurchaseItemDeleteError {
            get {
                return ResourceManager.GetString("AllPurchaseItemDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting purchase item... Please wait..
        /// </summary>
        internal static string AllPurchaseItemDeleting {
            get {
                return ResourceManager.GetString("AllPurchaseItemDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Items.
        /// </summary>
        internal static string AllPurchaseItemDisplayName {
            get {
                return ResourceManager.GetString("AllPurchaseItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify purchase items.
        /// </summary>
        internal static string AllPurchaseItemDisplayToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseItemDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load purchase items. Please contact support..
        /// </summary>
        internal static string AllPurchaseItemLoadError {
            get {
                return ResourceManager.GetString("AllPurchaseItemLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading purchase items... Please wait..
        /// </summary>
        internal static string AllPurchaseItemLoading {
            get {
                return ResourceManager.GetString("AllPurchaseItemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete purchase order ({0}). Please contact support..
        /// </summary>
        internal static string AllPurchaseOrderDeleteError {
            get {
                return ResourceManager.GetString("AllPurchaseOrderDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting purchase order... Please wait..
        /// </summary>
        internal static string AllPurchaseOrderDeleting {
            get {
                return ResourceManager.GetString("AllPurchaseOrderDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        internal static string AllPurchaseOrderDisplayName {
            get {
                return ResourceManager.GetString("AllPurchaseOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify purchase orders..
        /// </summary>
        internal static string AllPurchaseOrderDisplayToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseOrderDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load purchase orders. Please contact support..
        /// </summary>
        internal static string AllPurchaseOrderLoadError {
            get {
                return ResourceManager.GetString("AllPurchaseOrderLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading purchase orders... Please wait..
        /// </summary>
        internal static string AllPurchaseOrderLoading {
            get {
                return ResourceManager.GetString("AllPurchaseOrderLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user ({0}). Please contact support..
        /// </summary>
        internal static string AllUserDeleteError {
            get {
                return ResourceManager.GetString("AllUserDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user... Please wait..
        /// </summary>
        internal static string AllUserDeleting {
            get {
                return ResourceManager.GetString("AllUserDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string AllUserDisplayName {
            get {
                return ResourceManager.GetString("AllUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify users..
        /// </summary>
        internal static string AllUserDisplayToolTip {
            get {
                return ResourceManager.GetString("AllUserDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load users. Please contact support..
        /// </summary>
        internal static string AllUserLoadError {
            get {
                return ResourceManager.GetString("AllUserLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users... Please wait..
        /// </summary>
        internal static string AllUserLoading {
            get {
                return ResourceManager.GetString("AllUserLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete vehicle ({0}). Please contact support..
        /// </summary>
        internal static string AllVehicleDeleteError {
            get {
                return ResourceManager.GetString("AllVehicleDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting vehicle... Please wait..
        /// </summary>
        internal static string AllVehicleDeleting {
            get {
                return ResourceManager.GetString("AllVehicleDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string AllVehicleDisplayName {
            get {
                return ResourceManager.GetString("AllVehicleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify vehicles..
        /// </summary>
        internal static string AllVehicleDisplayToolTip {
            get {
                return ResourceManager.GetString("AllVehicleDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load vehicles. Please contact support..
        /// </summary>
        internal static string AllVehicleLoadError {
            get {
                return ResourceManager.GetString("AllVehicleLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading vehicles... Please wait..
        /// </summary>
        internal static string AllVehicleLoading {
            get {
                return ResourceManager.GetString("AllVehicleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string AppSettingsDisplayName {
            get {
                return ResourceManager.GetString("AppSettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to set application settings..
        /// </summary>
        internal static string AppSettingsDisplayToolTip {
            get {
                return ResourceManager.GetString("AppSettingsDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open log file..
        /// </summary>
        internal static string AppSettingsFailedToOpenLog {
            get {
                return ResourceManager.GetString("AppSettingsFailedToOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AssemblyInformationDisplayName {
            get {
                return ResourceManager.GetString("AssemblyInformationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Partner: {0}.
        /// </summary>
        internal static string BusinessPartnerDisplayName {
            get {
                return ResourceManager.GetString("BusinessPartnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save business partner ({0}) because it already exists..
        /// </summary>
        internal static string BusinessPartnerSaveError {
            get {
                return ResourceManager.GetString("BusinessPartnerSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving business partner... Please wait..
        /// </summary>
        internal static string BusinessPartnerSaving {
            get {
                return ResourceManager.GetString("BusinessPartnerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string ContentId {
            get {
                return ResourceManager.GetString("ContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardDisplayName {
            get {
                return ResourceManager.GetString("DashboardDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the database. Please contact support..
        /// </summary>
        internal static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} ({1})?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not match new password!.
        /// </summary>
        internal static string DontMatchError {
            get {
                return ResourceManager.GetString("DontMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download help document. Please contact support..
        /// </summary>
        internal static string HelpDocumentDowloadError {
            get {
                return ResourceManager.GetString("HelpDocumentDowloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate username ({0}). Please enter a valid password..
        /// </summary>
        internal static string LoginFailPassword {
            get {
                return ResourceManager.GetString("LoginFailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) was not found in the Database. Please enter a valid username..
        /// </summary>
        internal static string LoginFailUsername {
            get {
                return ResourceManager.GetString("LoginFailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user info... Please wait..
        /// </summary>
        internal static string LoginGettingUserInfo {
            get {
                return ResourceManager.GetString("LoginGettingUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) not found. Please contact support..
        /// </summary>
        internal static string LoginLoadError {
            get {
                return ResourceManager.GetString("LoginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user settings... Please wait..
        /// </summary>
        internal static string LoginLoading {
            get {
                return ResourceManager.GetString("LoginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TCMS!!! Please enter your username and password to login..
        /// </summary>
        internal static string LoginStart {
            get {
                return ResourceManager.GetString("LoginStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your current password to change it to the new password..
        /// </summary>
        internal static string LoginVerify {
            get {
                return ResourceManager.GetString("LoginVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutDisplayName {
            get {
                return ResourceManager.GetString("LogoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log out of the application..
        /// </summary>
        internal static string LogoutDisplayToolTip {
            get {
                return ResourceManager.GetString("LogoutDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Part: {0}.
        /// </summary>
        internal static string MaintenancePartDisplayName {
            get {
                return ResourceManager.GetString("MaintenancePartDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Part: {0}.
        /// </summary>
        internal static string MaintenancePartDisplayToolTip {
            get {
                return ResourceManager.GetString("MaintenancePartDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save maintenance part ({0}). Please contact support..
        /// </summary>
        internal static string MaintenancePartSaveError {
            get {
                return ResourceManager.GetString("MaintenancePartSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving maintenance part... Please wait..
        /// </summary>
        internal static string MaintenancePartSaving {
            get {
                return ResourceManager.GetString("MaintenancePartSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Record Detail: {0}.
        /// </summary>
        internal static string MaintenanceRecordDetailDisplayName {
            get {
                return ResourceManager.GetString("MaintenanceRecordDetailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Record Detail: {0}.
        /// </summary>
        internal static string MaintenanceRecordDetailDisplayToolTip {
            get {
                return ResourceManager.GetString("MaintenanceRecordDetailDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save maintenance record detail ({0}). Please contact support..
        /// </summary>
        internal static string MaintenanceRecordDetailSaveError {
            get {
                return ResourceManager.GetString("MaintenanceRecordDetailSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving maintenance record detail... Please wait..
        /// </summary>
        internal static string MaintenanceRecordDetailSaving {
            get {
                return ResourceManager.GetString("MaintenanceRecordDetailSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Record: {0}.
        /// </summary>
        internal static string MaintenanceRecordDisplayName {
            get {
                return ResourceManager.GetString("MaintenanceRecordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Record: {0}.
        /// </summary>
        internal static string MaintenanceRecordDisplayToolTip {
            get {
                return ResourceManager.GetString("MaintenanceRecordDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save maintenance record ({0}). Please contact support..
        /// </summary>
        internal static string MaintenanceRecordSaveError {
            get {
                return ResourceManager.GetString("MaintenanceRecordSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving maintenance record... Please wait..
        /// </summary>
        internal static string MaintenanceRecordSaving {
            get {
                return ResourceManager.GetString("MaintenanceRecordSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for background task to complete before closing or logging out of the application..
        /// </summary>
        internal static string MainWindowBackgroundTask {
            get {
                return ResourceManager.GetString("MainWindowBackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS - {0}.
        /// </summary>
        internal static string MainWindowDisplayName {
            get {
                return ResourceManager.GetString("MainWindowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS - {0} - ({1}).
        /// </summary>
        internal static string MainWindowDisplayNameLoggedIn {
            get {
                return ResourceManager.GetString("MainWindowDisplayNameLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Help Menu..
        /// </summary>
        internal static string MainWindowHelpTooltip {
            get {
                return ResourceManager.GetString("MainWindowHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MainWindowInitialStatus {
            get {
                return ResourceManager.GetString("MainWindowInitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading window... Please wait..
        /// </summary>
        internal static string MainWindowLoadingWindow {
            get {
                return ResourceManager.GetString("MainWindowLoadingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Main Menu..
        /// </summary>
        internal static string MainWindowMenuTooltip {
            get {
                return ResourceManager.GetString("MainWindowMenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed... Please contact support if this error continues to occur..
        /// </summary>
        internal static string MainWindowUnexpectedLoginError {
            get {
                return ResourceManager.GetString("MainWindowUnexpectedLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user name... Please contact support..
        /// </summary>
        internal static string MainWindowUserUnknown {
            get {
                return ResourceManager.GetString("MainWindowUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more unsaved changes were found. Are you sure you want to continue without saving?.
        /// </summary>
        internal static string MainWindowViewModelCheckForChanges {
            get {
                return ResourceManager.GetString("MainWindowViewModelCheckForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest: {0}.
        /// </summary>
        internal static string ManifestDisplayName {
            get {
                return ResourceManager.GetString("ManifestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest: {0}.
        /// </summary>
        internal static string ManifestDisplayToolTip {
            get {
                return ResourceManager.GetString("ManifestDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save manifest ({0}). Please contact support..
        /// </summary>
        internal static string ManifestSaveError {
            get {
                return ResourceManager.GetString("ManifestSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving manifest...Please wait..
        /// </summary>
        internal static string ManifestSaving {
            get {
                return ResourceManager.GetString("ManifestSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        internal static string MyInfoDisplayName {
            get {
                return ResourceManager.GetString("MyInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Manifests.
        /// </summary>
        internal static string MyManifestDisplayName {
            get {
                return ResourceManager.GetString("MyManifestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening link to {0}... Please wait..
        /// </summary>
        internal static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open link... Please contact support..
        /// </summary>
        internal static string OpenLinkError {
            get {
                return ResourceManager.GetString("OpenLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part: {0}.
        /// </summary>
        internal static string PartDisplayName {
            get {
                return ResourceManager.GetString("PartDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part: {0}.
        /// </summary>
        internal static string PartDisplayToolTip {
            get {
                return ResourceManager.GetString("PartDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save part ({0}) because it already exists..
        /// </summary>
        internal static string PartSaveError {
            get {
                return ResourceManager.GetString("PartSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving part... Please wait..
        /// </summary>
        internal static string PartSaving {
            get {
                return ResourceManager.GetString("PartSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll: {0}.
        /// </summary>
        internal static string PayrollDisplayName {
            get {
                return ResourceManager.GetString("PayrollDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll: {0}.
        /// </summary>
        internal static string PayrollDisplayToolTip {
            get {
                return ResourceManager.GetString("PayrollDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save payroll. Please contact support..
        /// </summary>
        internal static string PayrollSaveError {
            get {
                return ResourceManager.GetString("PayrollSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving payroll... Please wait..
        /// </summary>
        internal static string PayrollSaving {
            get {
                return ResourceManager.GetString("PayrollSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Item: {0}.
        /// </summary>
        internal static string PurchaseItemDisplayName {
            get {
                return ResourceManager.GetString("PurchaseItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Item: {0}.
        /// </summary>
        internal static string PurchaseItemDisplayToolTip {
            get {
                return ResourceManager.GetString("PurchaseItemDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save purchase item ({0}). Please contact support..
        /// </summary>
        internal static string PurchaseItemSaveError {
            get {
                return ResourceManager.GetString("PurchaseItemSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving purchase item... Please wait..
        /// </summary>
        internal static string PurchaseItemSaving {
            get {
                return ResourceManager.GetString("PurchaseItemSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order: {0}.
        /// </summary>
        internal static string PurchaseOrderDisplayName {
            get {
                return ResourceManager.GetString("PurchaseOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order: {0}.
        /// </summary>
        internal static string PurchaseOrderDisplayToolTip {
            get {
                return ResourceManager.GetString("PurchaseOrderDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save purchase order ({0}). Please contact support..
        /// </summary>
        internal static string PurchaseOrderSaveError {
            get {
                return ResourceManager.GetString("PurchaseOrderSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving purchase order... Please wait..
        /// </summary>
        internal static string PurchaseOrderSaving {
            get {
                return ResourceManager.GetString("PurchaseOrderSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportDisplayName {
            get {
                return ResourceManager.GetString("ReportDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to run reports..
        /// </summary>
        internal static string ReportDisplayToolTip {
            get {
                return ResourceManager.GetString("ReportDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write report to excel file... Please verify the file is not open already..
        /// </summary>
        internal static string ReportExportFailedError {
            get {
                return ResourceManager.GetString("ReportExportFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting report to Excel... Please wait..
        /// </summary>
        internal static string ReportExporting {
            get {
                return ResourceManager.GetString("ReportExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string ReportFileFilter {
            get {
                return ResourceManager.GetString("ReportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading report... Please wait..
        /// </summary>
        internal static string ReportLoading {
            get {
                return ResourceManager.GetString("ReportLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load report. Please contact support..
        /// </summary>
        internal static string ReportRunFailedError {
            get {
                return ResourceManager.GetString("ReportRunFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by any column..
        /// </summary>
        internal static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeDisplayName {
            get {
                return ResourceManager.GetString("ThemeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify application theme..
        /// </summary>
        internal static string ThemeDisplayToolTip {
            get {
                return ResourceManager.GetString("ThemeDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user theme... Please wait..
        /// </summary>
        internal static string ThemeLoading {
            get {
                return ResourceManager.GetString("ThemeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving theme... Please wait..
        /// </summary>
        internal static string ThemeSaving {
            get {
                return ResourceManager.GetString("ThemeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMS.
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while {0}.{1}Please contact support with the following error ID: {2}.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string UserDisplayName {
            get {
                return ResourceManager.GetString("UserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string UserDisplayToolTip {
            get {
                return ResourceManager.GetString("UserDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user ({0}) because it already exists..
        /// </summary>
        internal static string UserSaveError {
            get {
                return ResourceManager.GetString("UserSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user... Please wait..
        /// </summary>
        internal static string UserSaving {
            get {
                return ResourceManager.GetString("UserSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle: {0}.
        /// </summary>
        internal static string VehicleDisplayName {
            get {
                return ResourceManager.GetString("VehicleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle: {0}.
        /// </summary>
        internal static string VehicleDisplayToolTip {
            get {
                return ResourceManager.GetString("VehicleDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save vehicle ({0}). Please contact support..
        /// </summary>
        internal static string VehicleSaveError {
            get {
                return ResourceManager.GetString("VehicleSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving vehicle... Please wait..
        /// </summary>
        internal static string VehicleSaving {
            get {
                return ResourceManager.GetString("VehicleSaving", resourceCulture);
            }
        }
    }
}
