//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS499.TCMS.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS499.TCMS.View.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate username ({0}). Please enter a valid password..
        /// </summary>
        internal static string LoginFailPassword {
            get {
                return ResourceManager.GetString("LoginFailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) was not found in the Active Directory. Please enter a valid username..
        /// </summary>
        internal static string LoginFailUsername {
            get {
                return ResourceManager.GetString("LoginFailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ({0}) not found. Please contact support..
        /// </summary>
        internal static string LoginLoadError {
            get {
                return ResourceManager.GetString("LoginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user settings... Please wait..
        /// </summary>
        internal static string LoginLoading {
            get {
                return ResourceManager.GetString("LoginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Windows username and password to login..
        /// </summary>
        internal static string LoginStart {
            get {
                return ResourceManager.GetString("LoginStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutDisplayName {
            get {
                return ResourceManager.GetString("LogoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log out of the application..
        /// </summary>
        internal static string LogoutDisplayToolTip {
            get {
                return ResourceManager.GetString("LogoutDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for background task to complete before closing or logging out of the application..
        /// </summary>
        internal static string MainWindowBackgroundTask {
            get {
                return ResourceManager.GetString("MainWindowBackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBT - {0}.
        /// </summary>
        internal static string MainWindowDisplayName {
            get {
                return ResourceManager.GetString("MainWindowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBT - {0} - ({1}).
        /// </summary>
        internal static string MainWindowDisplayNameLoggedIn {
            get {
                return ResourceManager.GetString("MainWindowDisplayNameLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Help Menu..
        /// </summary>
        internal static string MainWindowHelpTooltip {
            get {
                return ResourceManager.GetString("MainWindowHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MainWindowInitialStatus {
            get {
                return ResourceManager.GetString("MainWindowInitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the Main Menu..
        /// </summary>
        internal static string MainWindowMenuTooltip {
            get {
                return ResourceManager.GetString("MainWindowMenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed... Please contact support if this error continues to occur..
        /// </summary>
        internal static string MainWindowUnexpectedLoginError {
            get {
                return ResourceManager.GetString("MainWindowUnexpectedLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user name... Please contact support..
        /// </summary>
        internal static string MainWindowUserUnknown {
            get {
                return ResourceManager.GetString("MainWindowUserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more unsaved changes were found. Are you sure you want to continue without saving?.
        /// </summary>
        internal static string MainWindowViewModelCheckForChanges {
            get {
                return ResourceManager.GetString("MainWindowViewModelCheckForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeDisplayName {
            get {
                return ResourceManager.GetString("ThemeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify application theme..
        /// </summary>
        internal static string ThemeDisplayToolTip {
            get {
                return ResourceManager.GetString("ThemeDisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user theme... Please wait..
        /// </summary>
        internal static string ThemeLoading {
            get {
                return ResourceManager.GetString("ThemeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving theme... Please wait..
        /// </summary>
        internal static string ThemeSaving {
            get {
                return ResourceManager.GetString("ThemeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBT.
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while {0}.{1}Please contact support with the following error ID: {2}.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
